### ISSUE TITLE
cookie

### ISSUE THREAD

**Issue by wehaha** [qq519043202/BILI#3]

**Comment by wehaha** [comment]
抱歉 问下 怎么弄到cookie啊   cookie是遗传数字字母吗？  还是DedeUserID  等对应不同的字母啊？

**Comment by Tmn07** [comment]
您好,我这里是手动从浏览器开发者工具中,把登入时的cookie复制下来.保存成文件bilicookies
cookie就是一堆参数 xxx=12314; yyy=123312;之类的
刚才试了一下 dosign.py  还是可以用的.刚才在网页上签到过了,所以提示已签到.
![image](https://user-images.githubusercontent.com/12949091/38036731-ef59e210-32d9-11e8-8c0d-d1b7c81140ac.png)

**Comment by wehaha** [comment]
您能帮忙看看 这是怎么回事吗？
运行 python dosign.py 后 出现

Traceback (most recent call last):
  File "dosign.py", line 26, in <module>
    do_sign(headers)
  File "dosign.py", line 13, in do_sign
    r = requests.get(url,headers=headers)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 60, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 362, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 308, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1039, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1072, in _send_request
    self.putheader(hdr, value)
  File "/usr/lib/python2.7/httplib.py", line 1017, in putheader
    raise ValueError('Invalid header value %r' % (one_value,))
ValueError: Invalid header value 'dssid=719****b9c07d98; fts=148***3441; pgv_pvi=8232852480; rpdid=olkkkossoqdoploiilsww; buvid3=03AB56C2-8C13-46DB-AB0A-E5EFDC4861094024infoc; uTZ=-480; LIVE_BUVID=9b6016aea645a373f0127f68e1f2455f; LIVE_BUVID__ckMd5=2ec2972c0346c33c; dsess=BAh7CEkiD3Nlc3Npb25faWQGOgZFVEki*********MjMGOwBG%0ASSIJY3NyZgY7AEZJIiUwNmVlNGNlYjA5ZDc0ZGE2O******DkxMWMyOWU4%0AOQY7AEZJIg10cmFja2luZwY7AEZ7B0kiFEhUVFBfVVNFUl9BR0VOVAY7AFRJ%0AIi0xYTY1ODg2NmYwYmFmMjZhMjVkNmFiZWZlNmQ4YTk3N2U4YTUwMmRhBjsA%0ARkkiGU*****BUX0xBTkdVQUdFBjsAVEkiLWNhNGFlZTBlODEyMTRh%0AZGRjNWZiMTI4NzdjZjllNWM4YjhiZWI3ZDYGOwBG%0A--3b47fd******533009cf9a***3d71f513ec; _qddaz=QD.4tjunc.j3****.j47225qg; sid=ii1t****18; im_notify_type_83***39=0; finger=ed****a; DedeUserID=835**9; DedeUserID__ckMd5=8f*********ff05; SESSDATA=57bab883%2C15247***C2b71f213; bili_jct=66607************9414f; _dfcaptcha=47f2a*****c971331752af979f49\n'

**Comment by Tmn07** [comment]
不大清楚.感觉是你cookie的问题.bilicookies这个文件就保存成这样子.实在不行的话你加我qq,聊一下看看
![image](https://user-images.githubusercontent.com/12949091/38094065-5797ff2c-339f-11e8-9703-453f5bf08f46.png)

**Comment by wehaha** [comment]
您看一下  我的是这个样子
​

2018-03-29 22:22 GMT+08:00 Tmn07 <notifications@github.com>:

**Comment by wehaha** [comment]
我只用签到功能  是不是也需要在bi.run（） 里添加参数啊？

**Comment by Tmn07** [comment]
签到功能只在dosign.py里,没有用到那个类呀

**Comment by VergeDX** [comment]
我也是这样
JSON 格式的 Cookie 貌似没办法用
